#  docker-compose -f docker-compose.yml config check validate config
version: "3.8"
services:
  shopsthai-web2:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        VITE_SSO_AUTH_SERVER: ${VITE_SSO_AUTH_SERVER}
        VITE_SSO_REALM: ${VITE_SSO_REALM}
        VITE_SSO_CLIENTID: ${VITE_SSO_CLIENTID}
        VITE_API_URL: ${VITE_API_URL}
    image: "shopsthai-web2:alpine"
    labels:
      com.docker.compose.project: "shopsthai-web2"
      virtual.host: "web2.shopsthai.com"
      virtual.tls-email: limweb@hotmail.com
      virtual.port: "8080" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./dist:/srv/www
    env_file:
      - .env
    environment:
      TZ: Asia/Bangkok
    logging:
      driver: "json-file" # ใช้ json-file driver (default)
      options:
        max-size: "10m" # จำกัดขนาดของแต่ละไฟล์ log ไม่ให้เกิน 10MB
        max-file: "5" # เก็บไฟล์ log ไว้สูงสุด 5 ไฟล์

networks:
  default:
    external: true
    name: proxy-network
